### ISSUE TITLE
Support components whose transforms vary across designspace

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontmake-rs#125]
The code in #123 currently makes the simplifying assumption that the components, including the transform, are identical across the design space. The Lexend - see https://github.com/googlefonts/lexend - Hbar violates that; support it.

For reference, at time of writing IR for Hbar is:

```yml
name: Hbar
instances:
- location:
    Hyper Expansion: 1.0
    Weight: 0.0
  instance:
    width: 1010.0
    height: null
    contours:
    - - !MoveTo
        x: 24.0
        y: 541.0
      - !LineTo
        x: 184.0
        y: 541.0
      - !LineTo
        x: 196.0
        y: 541.0
      - !LineTo
        x: 815.0
        y: 541.0
      - !LineTo
        x: 824.0
        y: 541.0
      - !LineTo
        x: 985.0
        y: 541.0
      - !LineTo
        x: 985.0
        y: 562.0
      - !LineTo
        x: 824.0
        y: 562.0
      - !LineTo
        x: 815.0
        y: 562.0
      - !LineTo
        x: 196.0
        y: 562.0
      - !LineTo
        x: 185.0
        y: 562.0
      - !LineTo
        x: 24.0
        y: 562.0
      - !LineTo
        x: 24.0
        y: 541.0
      - ClosePath
    components:
    - base: H
      transform:
      - 1.0
      - 0.0
      - 0.0
      - 1.0
      - -15.0
      - 0.0
- location:
    Hyper Expansion: 1.0
    Weight: 1.0
  instance:
    width: 1225.0
    height: null
    contours:
    - - !MoveTo
        x: 105.0
        y: 488.0
      - !LineTo
        x: 296.0
        y: 488.0
      - !LineTo
        x: 375.0
        y: 498.0
      - !LineTo
        x: 854.0
        y: 498.0
      - !LineTo
        x: 949.0
        y: 488.0
      - !LineTo
        x: 1121.0
        y: 488.0
      - !LineTo
        x: 1121.0
        y: 652.0
      - !LineTo
        x: 959.0
        y: 652.0
      - !LineTo
        x: 842.0
        y: 642.0
      - !LineTo
        x: 385.0
        y: 642.0
      - !LineTo
        x: 286.0
        y: 652.0
      - !LineTo
        x: 105.0
        y: 652.0
      - !LineTo
        x: 105.0
        y: 488.0
      - ClosePath
    components:
    - base: H
      transform:
      - 1.0
      - 0.0
      - 0.0
      - 1.0
      - 64.0
      - 0.0
- location:
    Hyper Expansion: 0.0
    Weight: 0.14432989
  instance:
    width: 744.0
    height: null
    contours:
    - - !MoveTo
        x: 28.0
        y: 536.0
      - !LineTo
        x: 117.0
        y: 536.0
      - !LineTo
        x: 148.0
        y: 536.0
      - !LineTo
        x: 600.0
        y: 536.0
      - !LineTo
        x: 623.0
        y: 536.0
      - !LineTo
        x: 716.0
        y: 536.0
      - !LineTo
        x: 716.0
        y: 582.0
      - !LineTo
        x: 618.0
        y: 582.0
      - !LineTo
        x: 601.0
        y: 582.0
      - !LineTo
        x: 143.0
        y: 582.0
      - !LineTo
        x: 117.0
        y: 582.0
      - !LineTo
        x: 28.0
        y: 582.0
      - !LineTo
        x: 28.0
        y: 536.0
      - ClosePath
    components:
    - base: H
      transform:
      - 1.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - 0.0
- location:
    Hyper Expansion: 0.0
    Weight: 1.0
  instance:
    width: 793.0
    height: null
    contours:
    - - !MoveTo
        x: 17.0
        y: 488.0
      - !LineTo
        x: 90.0
        y: 488.0
      - !LineTo
        x: 179.0
        y: 498.0
      - !LineTo
        x: 595.0
        y: 498.0
      - !LineTo
        x: 703.0
        y: 488.0
      - !LineTo
        x: 780.0
        y: 488.0
      - !LineTo
        x: 780.0
        y: 652.0
      - !LineTo
        x: 703.0
        y: 652.0
      - !LineTo
        x: 583.0
        y: 642.0
      - !LineTo
        x: 189.0
        y: 642.0
      - !LineTo
        x: 90.0
        y: 652.0
      - !LineTo
        x: 17.0
        y: 652.0
      - !LineTo
        x: 17.0
        y: 488.0
      - ClosePath
    components:
    - base: H
      transform:
      - 1.0
      - 0.0
      - 0.0
      - 1.0
      - 2.0
      - 0.0
- location:
    Hyper Expansion: 0.0
    Weight: 0.44329897
  instance:
    width: 857.0
    height: null
    contours:
    - - !MoveTo
        x: 57.0
        y: 468.0
      - !LineTo
        x: 163.0
        y: 468.0
      - !LineTo
        x: 209.0
        y: 478.0
      - !LineTo
        x: 625.0
        y: 478.0
      - !LineTo
        x: 656.0
        y: 468.0
      - !LineTo
        x: 800.0
        y: 468.0
      - !LineTo
        x: 800.0
        y: 572.0
      - !LineTo
        x: 649.0
        y: 572.0
      - !LineTo
        x: 613.0
        y: 562.0
      - !LineTo
        x: 219.0
        y: 562.0
      - !LineTo
        x: 173.0
        y: 572.0
      - !LineTo
        x: 57.0
        y: 572.0
      - !LineTo
        x: 57.0
        y: 468.0
      - ClosePath
    components:
    - base: H
      transform:
      - 1.0
      - 0.0
      - 0.0
      - 1.0
      - 48.0
      - 0.0
- location:
    Hyper Expansion: 0.0
    Weight: 0.0
  instance:
    width: 731.0
    height: null
    contours:
    - - !MoveTo
        x: 24.0
        y: 541.0
      - !LineTo
        x: 116.0
        y: 541.0
      - !LineTo
        x: 126.0
        y: 541.0
      - !LineTo
        x: 609.0
        y: 541.0
      - !LineTo
        x: 614.0
        y: 541.0
      - !LineTo
        x: 706.0
        y: 541.0
      - !LineTo
        x: 706.0
        y: 562.0
      - !LineTo
        x: 614.0
        y: 562.0
      - !LineTo
        x: 608.0
        y: 562.0
      - !LineTo
        x: 126.0
        y: 562.0
      - !LineTo
        x: 118.0
        y: 562.0
      - !LineTo
        x: 24.0
        y: 562.0
      - !LineTo
        x: 24.0
        y: 541.0
      - ClosePath
    components:
    - base: H
      transform:
      - 1.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - 0.0
- location:
    Hyper Expansion: 1.0
    Weight: 0.44329897
  instance:
    width: 1289.0
    height: null
    contours:
    - - !MoveTo
        x: 145.0
        y: 468.0
      - !LineTo
        x: 301.0
        y: 468.0
      - !LineTo
        x: 337.0
        y: 478.0
      - !LineTo
        x: 964.0
        y: 478.0
      - !LineTo
        x: 985.0
        y: 468.0
      - !LineTo
        x: 1144.0
        y: 468.0
      - !LineTo
        x: 1144.0
        y: 572.0
      - !LineTo
        x: 988.0
        y: 572.0
      - !LineTo
        x: 952.0
        y: 562.0
      - !LineTo
        x: 347.0
        y: 562.0
      - !LineTo
        x: 301.0
        y: 572.0
      - !LineTo
        x: 145.0
        y: 572.0
      - !LineTo
        x: 145.0
        y: 468.0
      - ClosePath
    components:
    - base: H
      transform:
      - 1.0
      - 0.0
      - 0.0
      - 1.0
      - 110.0
      - 0.0
```
